#!/bin/bash

FILES="*.txt"

for f in $FILES; do
    read -r line < $f
    if [[ ${line:0:1} != "#" ]]
    then
        echo | cat - $f > temp && mv temp $f
        echo "#" | cat - $f > temp && mv temp $f
        echo "#" | cat - $f > temp && mv temp $f
        echo "#Outcome" | cat - $f > temp && mv temp $f
        echo "#Message" | cat - $f > temp && mv temp $f
        echo "#oll16" | cat - $f > temp && mv temp $f
        echo "#${f:0:${#f}-5}" | cat - $f > temp && mv temp $f
        echo "#${f:0:${#f}-4}" | cat - $f > temp && mv temp $f
    fi
done